-- MySQL Script generated by MySQL Workbench
-- 06/14/17 22:32:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sgi
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sgi` ;

-- -----------------------------------------------------
-- Schema sgi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sgi` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish2_ci ;
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema sgi_cms
-- -----------------------------------------------------
SHOW WARNINGS;
USE `sgi` ;

-- -----------------------------------------------------
-- Table `tipo_menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tipo_menu` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tipo_menu` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(30) CHARACTER SET 'utf8' NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `updated_by` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `descripcion_UNIQUE` ON `tipo_menu` (`descripcion` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `menu` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `menu` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `menu_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `tipo_menu_id` INT(10) UNSIGNED NOT NULL,
  `etiqueta` VARCHAR(25) CHARACTER SET 'utf8' NOT NULL,
  `url` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `posicion` TINYINT(3) UNSIGNED NOT NULL DEFAULT '1',
  `icono` VARCHAR(35) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `updated_by` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_menu_menu1`
    FOREIGN KEY (`menu_id`)
    REFERENCES `menu` (`id`),
  CONSTRAINT `fk_menu_tipo_menu1`
    FOREIGN KEY (`tipo_menu_id`)
    REFERENCES `tipo_menu` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rol` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `rol` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL,
  `observacion` VARCHAR(200) CHARACTER SET 'utf8' NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `updated_by` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `descripcion_UNIQUE` ON `rol` (`descripcion` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `menu_rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `menu_rol` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `menu_rol` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `menu_id` INT(10) UNSIGNED NOT NULL,
  `rol_id` INT(10) UNSIGNED NOT NULL,
  `estado` TINYINT(3) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `updated_by` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_menu_rol_menu1`
    FOREIGN KEY (`menu_id`)
    REFERENCES `menu` (`id`),
  CONSTRAINT `fk_menu_rol_rol1`
    FOREIGN KEY (`rol_id`)
    REFERENCES `rol` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;

SHOW WARNINGS;
CREATE INDEX `fk_menu_rol_menu1_idx` ON `menu_rol` (`menu_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `migrations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `migrations` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `migrations` (
  `version` BIGINT(20) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `permiso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `permiso` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `permiso` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `nombre_a_mostrar` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `observacion` VARCHAR(200) CHARACTER SET 'utf8' NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL,
  `created_by` INT(11) NOT NULL,
  `updated_by` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `nombre_UNIQUE` ON `permiso` (`nombre` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `nombre_a_mostrar_UNIQUE` ON `permiso` (`nombre_a_mostrar` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `permiso_rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `permiso_rol` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `permiso_rol` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `permiso_id` INT(10) UNSIGNED NOT NULL,
  `rol_id` INT(10) UNSIGNED NOT NULL,
  `estado` TINYINT(3) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `updated_by` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_permiso_rol_rol1`
    FOREIGN KEY (`rol_id`)
    REFERENCES `rol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rolo_permiso_permisos1`
    FOREIGN KEY (`permiso_id`)
    REFERENCES `permiso` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;

SHOW WARNINGS;
CREATE INDEX `fk_rolo_permiso_permisos1_idx` ON `permiso_rol` (`permiso_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `sgi_session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgi_session` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `sgi_session` (
  `id` VARCHAR(40) NOT NULL,
  `ip_address` VARCHAR(45) NOT NULL,
  `timestamp` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `data` BLOB NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

SHOW WARNINGS;
CREATE INDEX `sgi_sessions_timestamp` ON `sgi_session` (`timestamp` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `departamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `departamento` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `departamento` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(30) CHARACTER SET 'utf8' NOT NULL,
  `observacion` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `updated_by` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `descripcion_UNIQUE` ON `departamento` (`descripcion` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `usuario` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `departamento_id` INT(10) UNSIGNED NOT NULL,
  `avatar` VARCHAR(45) NULL,
  `usuario` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `password` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `estado` TINYINT(3) UNSIGNED NOT NULL,
  `email` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `updated_by` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_usuario_departamento1`
    FOREIGN KEY (`departamento_id`)
    REFERENCES `departamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `usuario_UNIQUE` ON `usuario` (`usuario` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `usuario_rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuario_rol` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `usuario_rol` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `usuario_id` INT(10) UNSIGNED NOT NULL,
  `rol_id` INT(10) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `updated_by` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_usuario_rol_rol`
    FOREIGN KEY (`rol_id`)
    REFERENCES `rol` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usuario_rol_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;

SHOW WARNINGS;
CREATE INDEX `fk_usuario_rol_rol_idx` ON `usuario_rol` (`rol_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tipo_periferico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tipo_periferico` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tipo_periferico` (
  `id_tipo_periferico` INT NOT NULL,
  `tipo_perifericocol` VARCHAR(45) NULL,
  `periferico_id_periferico` INT(11) NOT NULL,
  PRIMARY KEY (`id_tipo_periferico`),
  CONSTRAINT `fk_tipo_periferico_periferico1`
    FOREIGN KEY (`periferico_id_periferico`)
    REFERENCES `sgi_cms`.`periferico` (`id_periferico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `rol`
-- -----------------------------------------------------
START TRANSACTION;
USE `sgi`;
INSERT INTO `rol` (`id`, `descripcion`, `observacion`, `created_at`, `updated_at`, `created_by`, `updated_by`) VALUES (1, 'SuperAdministrador', 'Rol Con todos los privilegios de la plataforma y admin/*.', '2017-06-02 12:10:06', '2017-06-12 11:50:03', 1, 0);
INSERT INTO `rol` (`id`, `descripcion`, `observacion`, `created_at`, `updated_at`, `created_by`, `updated_by`) VALUES (2, 'Operador', 'Permite a los usuarios Manipular las acciones de Operador', '2017-06-02 12:10:06', '2017-06-13 20:35:45', 1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `departamento`
-- -----------------------------------------------------
START TRANSACTION;
USE `sgi`;
INSERT INTO `departamento` (`id`, `descripcion`, `observacion`, `created_at`, `updated_at`, `created_by`, `updated_by`) VALUES (1, 'System', 'Grupo de Sistemas', '2017-06-13 20:58:38', '2017-06-13 20:58:38', 1, 0);

COMMIT;


-- -----------------------------------------------------
-- Data for table `usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `sgi`;
INSERT INTO `usuario` (`id`, `departamento_id`, `avatar`, `usuario`, `nombre`, `apellido`, `password`, `estado`, `email`, `created_at`, `updated_at`, `created_by`, `updated_by`) VALUES (1, 1, 'avatar.png', 'admin', 'Super', 'Administrador', '5125c356c48ae203a45ae894443f9d323f040de96910f9dc1b973c35e09f2dfb', 1, 'tebasde@gmail.com', '2017-06-02 12:10:06', '2017-06-07 10:13:11', 1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `usuario_rol`
-- -----------------------------------------------------
START TRANSACTION;
USE `sgi`;
INSERT INTO `usuario_rol` (`id`, `usuario_id`, `rol_id`, `created_at`, `updated_at`, `created_by`, `updated_by`) VALUES (1, 1, 1, '2017-06-02 12:10:06', '2017-06-12 11:50:03', 1, 0);

COMMIT;

